# .goreleaser.yaml
version: 2

project_name: ghkd

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./main.go
    binary: ghkd

archives:
  - format: binary
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
