# .goreleaser.yaml
version: 2

project_name: ghkd

builds:
  - env:
      - CGO_ENABLED=0 # Set to 0 for static binaries (recommended for Linux)
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # The main file path
    main: ./main.go
    binary: ghkd

archives:
  - format: tar.gz
    # This creates a folder structure inside the archive
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
