# .goreleaser.yaml
version: 2

project_name: ghkd

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ghkd
    binary: ghkd

archives:
  - format: binary
    # This template will name the file like: ghkd_linux_amd64
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
